apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-admin-user
spec:
  data:
    - secretKey: RABBITMQ_ADMIN_USERNAME
      remoteRef:
        key: kv/underdark/openstack/rabbitmq-admin-user
        property: RABBITMQ_ADMIN_USERNAME
    - secretKey: RABBITMQ_ADMIN_PASSWORD
      remoteRef:
        key: kv/underdark/openstack/rabbitmq-admin-user
        property: RABBITMQ_ADMIN_PASSWORD
    - secretKey: RABBITMQ_GUEST_PASSWORD
      remoteRef:
        key: kv/underdark/openstack/rabbitmq-admin-user
        property: RABBITMQ_GUEST_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: rabbitmq-admin-user
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-erlang-cookie
spec:
  data:
    - secretKey: erlang_cookie
      remoteRef:
        key: kv/underdark/openstack/rabbitmq-erlang-cookie
        property: erlang_cookie
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: rabbitmq-erlang-cookie
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
