$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-erlang-cookie
#  namespace: openstack
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-admin-user
#  namespace: openstack
