apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keystone-keystone-admin
spec:
  data:
    - secretKey: password
      remoteRef:
        key: kv/underdark/openstack/keystone-admin
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: keystone-keystone-admin
    template:
      engineVersion: v2
      data:
        OS_AUTH_URL: "http://keystone-api.openstack.svc.cluster.local:5000/v3"
        OS_REGION_NAME: "RegionOne"
        OS_INTERFACE: "internal"
        OS_PROJECT_DOMAIN_NAME: "default"
        OS_PROJECT_NAME: "admin"
        OS_USER_DOMAIN_NAME: "default"
        OS_USERNAME: "admin"
        OS_PASSWORD: "{{ .password }}"
        OS_DEFAULT_DOMAIN: "default"
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keystone-db-admin
spec:
  data:
    - secretKey: password
      remoteRef:
        key: kv/underdark/openstack/mariadb-admin
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: keystone-db-admin
    template:
      engineVersion: v2
      data:
        DB_CONNECTION: "mysql+pymysql://root:{{ .password }}@mariadb.openstack.svc.cluster.local:3306/keystone?charset=utf8"
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keystone-db-user
spec:
  data:
    - secretKey: password
      remoteRef:
        key: kv/underdark/openstack/keystone-db-user
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: keystone-db-user
    template:
      engineVersion: v2
      data:
        DB_CONNECTION: "mysql+pymysql://keystone:{{ .password }}@mariadb.openstack.svc.cluster.local:3306/keystone?charset=utf8"
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keystone-rabbitmq-admin
spec:
  data:
    - secretKey: username
      remoteRef:
        key: kv/underdark/openstack/rabbitmq-admin-user
        property: RABBITMQ_ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: kv/underdark/openstack/rabbitmq-admin-user
        property: RABBITMQ_ADMIN_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: keystone-rabbitmq-admin
    template:
      engineVersion: v2
      data:
        RABBITMQ_CONNECTION: "rabbit://{{ .username }}:{{ .password }}@rabbitmq.openstack.svc.cluster.local:5672/keystone"
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keystone-rabbitmq-user
spec:
  data:
    - secretKey: password
      remoteRef:
        key: kv/underdark/openstack/keystone-rabbitmq-user
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: keystone-rabbitmq-user
    template:
      engineVersion: v2
      data:
        RABBITMQ_CONNECTION: "rabbit://keystone:{{ .password }}@rabbitmq.openstack.svc.cluster.local:5672/keystone"
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
