$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: keystone-keystone-admin
#  namespace: openstack
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: keystone-db-admin
#  namespace: openstack
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: keystone-db-user
#  namespace: openstack
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: keystone-rabbitmq-admin
#  namespace: openstack
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: keystone-rabbitmq-user
#  namespace: openstack
