apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: libvirt-etc
spec:
  data:
    - secretKey: qemu.conf
      remoteRef:
        key: kv/underdark/openstack/libvirt-qemu.conf
        property: qemu.conf
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: libvirt-etc
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: libvirt-libvirt-default-etc
spec:
  data:
    - secretKey: qemu.conf
      remoteRef:
        key: kv/underdark/openstack/libvirt-qemu.conf
        property: qemu.conf
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: libvirt-libvirt-default-etc
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
