$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: libvirt-etc
#  namespace: openstack
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: libvirt-libvirt-default-etc
#  namespace: openstack
